// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: guide-multipane
:projectid: graphql-intro
:page-duration: 15 minutes
:page-releasedate: 2020-06-17
:page-description: Learn how to create and test a GraphQL service using MicroProfile GraphQL and Open Liberty.
:guide-author: Open Liberty
:page-related-guides: ['cdi-intro', 'rest-intro']
:page-guide-category: microprofile
:page-essential: false
:page-permalink: /guides/{projectid}
:common-includes: ../guides-common/
:imagesdir: /img/guide/{projectid}
:page-seo-title: Creating a GraphQL service and GrahQL client
:page-seo-description: Find out how to create and test a GraphQL service on Open Liberty
= Creating and consuming a GraphQL web service

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form,
view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Explore how to create a GraphQL web service and consume a GraphQL web service using template interfaces.

:graphiql-url: http://localhost:9080/api/graphiql.html
:schema-url: http://localhost:9080/api/graphql/schema.graphql

== What you'll learn

You'll learn how to create and test a microservice using MicroProfile GraphQL and Open Liberty.
You'll use Maven throughout the guide to build the microservice and deploy it
to run on the Open Liberty application server.

=== What is GraphQL
GraphQL is an open-source data query and manipulation language for APIs, and a runtime for fulfilling these queries with
existing data.

GraphQL queries specify the shape of the response data, which allows users to get exactly what data they want.
GraphQL APIs contain a single endpoint that handles queries. GraphQL APIs are defined by Types and Fields as opposed
to being defined by endpoints like REST APIs. This enables GraphQL APIs to operate on multiple resources in the single
query where REST APIs would require loading the data from multiple URLs.

You will create a GraphQL web service that queries, manipulates and stores album and artist information.
The artist and album resources are provided in JSON files.

///////////////////////////
// Getting started
///////////////////////////

[role='command']
link:https://raw.githubusercontent.com/OpenLiberty/guides-common/master/gitclone.adoc[]

///////////////////////////
// Try what you’ll build
///////////////////////////

[role='command']
link:https://raw.githubusercontent.com/OpenLiberty/guides-common/master/twyb-intro.adoc[]

//--** Describe what user should run and expect to see after running the complete version of the application.
You are provided with Graphiql, an interactive in-browser GraphQL IDE, which is served by the Open Liberty server.
You can use Graphiql to perform queries in with an interactive interface to assist in development and testing of the API.

Once the server is running, access {graphiql-url}[{graphiql-url}^].
Run the following query to get the artist data for Drake:

[role='command']
----
query {
    artist(artist: "Drake") {
        name
        genres
        albums {
            title
            year
            ntracks
        }
    }
}
----

Run the following query to request only the `name` and `genres` field of artists Drake and Rihanna.

[role='command']
----
query {
  artists(artists: ["Drake", "Rihanna"]) {
    name
    genres
  }
}
----

Run the following query to add a new artist to the service:

[role='command']
----
mutation {
  addArtist(artist: {
    name: "Elvis Presley",
    genres: "Rock and Roll",
    albums: [
      {
        title: "Elvis Presley"
        ntracks: 12
        year: "1956"
      }
    ]
  })
}
----

Access {schema-url}[{schema-url}^] to view the API schema.

[role='command']
link:https://raw.githubusercontent.com/OpenLiberty/guides-common/master/twyb-end.adoc[]

== Building the application

Navigate to the `start` directory

[role='command']
link:https://raw.githubusercontent.com/OpenLiberty/guides-common/master/devmode-start.adoc[]

=== Enabling GraphQL

The MicroProfile GraphQL feature enables GraphQL support for your application.
This feature is already enabled in the `configuration file`.

=== Creating the GraphQL API

In GraphQL, a single class should represent a single resource, or a group of resources of the same type.
In this application, artists and albums are the two resources. Since the two resources are related, they can be
represented by a single class.

The `start` folder already contains the data files, `artists.json` and `albums.json`, and their respective model classes,
`Album` and `Artist`.
The `start` folder also contains `JsonService`, a static class to deserialize the artist and album data from data files
into the model classes.

[role="code_command hotspot", subs="quotes"]
----
#Create the `ArtistService` class.#
`src/main/java/io/openliberty/guides/graphql/ArtistService.java`
----

The `@GraphQLApi` annotation indicates that `ArtistService` is a GraphQL endpoint.
Methods in this class can define GraphQL queries and annotations.

Entities are the objects used in GraphQL. An entity is created in the schema from a custom Java class when the class is
used as the return type or argument of a query or mutation method, or the return type of a method that has a
`@Source` annotation applied on an argument.

Queries are GraphQL requests that request all or specific fields of an object.
A GraphQL query is created in the schema for any method in `ArtistService` annotated with `@Query`.
The value parameter of the `@Query` annotation is used for the name of the GraphQL query.
If the value parameter is not provided, the method's name is used as the query's name.

Mutations are GraphQL requests that modify a resource.
A GraphQL mutation is created in the schema for any method in `ArtistService` annotated with `@Mutation`.
Similar to `@Query`, the value parameter of the `@Mutation` annotation is used for the name of the GraphQL mutation.
If the value parameter is not provided, the method's name is used as the query's name.

The value parameter of the `@Name` annotation is used for the name of the GraphQL query or mutation parameter.
If the value parameter is not provided, the method argument's name is used as the the query parameter's name.

The `@Name` parameter can also be used to change the name of an attribute used in a class that represents a GraphQL
entity. The value parameter of the `@Name` annotation is used for the field name in the corresponding GraphQL
entity.

=== Implementing queries

The `ArtistService` class contains two queries, `artist` and `artists`.

The `getArtist()` method implements the `artist` query, which retrieves the artist corresponding to the name supplied
by the argument `name`. When an artist is not found, a `GraphQLException` is thrown, which returns an `error` object
to the client.

The `getArtists()` method implements the `artists` query, which retrieves a list of artists corresponding to the list of
artist names supplied by the `names` argument. When artists in the list of names are not found, a `GraphQLException`
is thrown, which returns an `error` object containing the missing names to the client.

The `getArtists()` method gets all possible results instead of throwing a `GraphQLException` on the first unknown artist.
Since GraphQL handles partial results when an error occurs, the found artist objects are returned to the client
alongside the error when `GraphQLException` is thrown.

=== Implementing mutations

The `ArtistService` class contains two mutations, `addArtist` and `reset`.

The `addArtist()` method implements the `addArtist` mutation, which adds a new artist to the service. If an artist with
the same name already exists in the service, the `addArtist()` method throws a `GraphQLException`.

The artist to add to the service is passed to the `addArtist` query through the `artist` argument. When the entity
passed to the artist parameter does not contain an attribute in the `Artist` or `Album` class, the value is set as `null`.

When the `@NotNull` annotation is used on an attribute in the `Artist` and `Album` class, an error is thrown when the
entity passed to the `artist` parameter of `addArtist` does not contain that field or if the value of the field
is `null`.

The `reset()` method implements the `reset` mutation, which resets the data handled by the service to the data
deserialized from the JSON data files. This method returns the number of artists removed from the service when the
data is reset.

=== Extending the Artist entity

The `artist` argument (of type `Artist`) of  the `albumCount()` method is annotated with `@Source`.
Since the type `Artist` is returned by a GraphQL query, the `@Source` annotation adds the name of the method,
`albumCount` as a property to the `Artist` GraphQL entity.


ArtistService.java
[source,java,linenums,role='code_column hide_tags=comment']
----
include::src/main/java/io/openliberty/guides/graphql/ArtistService.java[]
----

//////////////////////////////////////////
// Running the application
//////////////////////////////////////////

[role='command']
link:https://raw.githubusercontent.com/OpenLiberty/guides-common/master/devmode-build.adoc[]

Access {schema-url}[{schema-url}^] to view the API schema.

The schema for this API looks like:

[role='no_copy']
----
type Album {
  ntracks: Int!
  title: String!
  year: String!
}

type Artist {
  albumCount: Int!
  albums: [Album]
  genres: String!
  name: String!
}

"Mutation root"
type Mutation {
  addArtist(artist: ArtistInput): Boolean!
  reset: Int!
}

"Query root"
type Query {
  artist(name: String): Artist
  artists(artists: [String]): [Artist]
}

input AlbumInput {
  ntracks: Int!
  title: String!
  year: String!
}

input ArtistInput {
  albums: [AlbumInput]
  genres: String!
  name: String!
}
----

The `!` in the schema indicates that the field of an entity (type or input), or the return value of a mutation, is
not `null`.

Notice that the schema lists `albumCount: Int!` as part of the type Artist, but `albumCount` is not an attribute of the
`Artist` class. The `@Source` annotation applied on the `artist` argument of `albumCount()` associates the return value
of the method, an integer, to the `albumCount` field of the GraphQL type Artist.

Access {graphiql-url}[{graphiql-url}^] to open Graphiql.

When you run a GraphQL query, you are required to specify the properties you want for an entity. The result object
has only the specified properties.

Run the following query to request the name and number of albums of The Beatles stored in `ArtistService`,
and the titles of their albums:

[role='command']
----
query {
  artist(name: "The Beatles") {
    name
    albumCount
    albums {
      title
    }
  }
}
----

Run the following query to request the name and title of albums of multiple artists, including an artist that does not
exist:

[role='command']
----
query {
  artists(names: ["Unknown", "Billie Holiday"]) {
    name
    albums {
      title
    }
  }
}
----

Notice that the result of the query contains both the error for the unknown artist and the partial results for the
query, which contains the artist objects for the artists that exist.

The above query can only get the same fields from multiple artist entities. Since GraphQL can support multiple queries
in a single request, you can get different fields for multiple artist entities by running the following request:

[role='command']
----
query {
  BillieHoliday: artist(name: "Billie Holiday") {
    name
    genres
  }
  Unknown: artist(name: "Unknown") {
    name
  }
  Drake: artist(name: "Drake") {
    name
    albumCount
  }
}
----

Similar to the `artists` query, this request also contains an error object for the unknown artist "Unknown", and results
for the other artists with different fields in each object.

Run the `addArtist` mutation to add a new artist to `ArtistService`.
Attempting to add an artist whose name already exists in the service results in an error.
Since all attributes of the `Artist` and `Album` classes are annotated with `@NotNull`, omitting a field or setting it
to `null` in the input `artist` for the following mutation will also result in an error.

[role='command']
----
mutation {
  addArtist(artist: {
    name: "Adele",
    genres: "Pop",
    albums: [
      {
        title: "19"
        ntracks: 12
        year: "2008"
      },
      {
        title: "21"
        ntracks: 11
        year: "2011"
      },
      {
        title: "25"
        ntracks: 11
        year: "2015"
      }
    ]
  })
}
----


== Testing the application

You can test this service manually by starting a server and pointing a web browser at the
{graphiql-url}[{graphiql-url}^] URL.
Automated tests are a much better approach because they trigger a failure if a change introduces a bug.
JUnit and the SmallRye GraphQL Client provide a simple environment to test the application.

=== Creating the GraphQL API client interface

The GraphQL Client API and its implementation are included as dependencies specified in your `pom.xml` file.
Look for the dependences with the `smallrye-graphql-client-api` and `smallrye-graphql-client` artifact IDs.

These dependencies provides the library that is required to implement the GraphQL Rest Client interface.

The GraphQL client API uses template interface to describe the remote service that you want to access.
The interface defines the queries and mutations to access as a method by mapping its annotations, return type and list
of arguments.

Since GraphQL requires that the required fields for an entity be sent with the query, the GraphQL client derives the
required fields from the attributes of the return type.
If the GraphQL client interface has a method annotated with `@Query` that maps the `artist` query and returns an
instance of the `Artist` class, the following query is requested from the GraphQL API:

[role='no_copy']
----
query {
  artist(name: ...) {
    name
    genres
    albums {
      title
      ntracks
      year
    }
  }
}
----

For the GraphQL client to query an artist with the `albumCount` field, you need to create a class that extends the
`Artist` class and contains the `albumCount` attribute.

[role="code_command hotspot", subs="quotes"]
----
#Create the `ArtistWithAlbumCount` class.#
`src/test/java/io/openliberty/guides/graphql/client/models/ArtistService.java`
----

The `albumCount` attribute extends the `Artist` class and contains the attribute `albumCount` that is annotated with
`@NotNull`.
If the GraphQL client interface has a method annotated with `@Query` that returns an instance of the
`ArtistWithAlbumCount` class, the following fields are requested from the GraphQL API:

[role='no_copy']
----
query {
  artist(name: ...) {
    name
    genres
    albumCount
    albums {
      title
      ntracks
      year
    }
  }
}
----

If you require a different subset of fields from the artist entity, you should create another class that maps to the
required fields.

Next, create a GraphQL client interface for the system service.
Write a template interface that maps the API of the artist service.

[role="code_command hotspot", subs="quotes"]
----
#Create the `ArtistServiceAPI` class.#
`src/test/java/io/openliberty/graphql/client/ArtistServiceAPI.java`
----

The `ArtistServiceAPI` interface contains two methods annotated with `@Mutation`, the `addArtist()` method that maps
to the `addArtist` mutation and the `reset()` method that maps to the `reset` mutation.
The interface contains four methods annotated with `@Query`. The `artist` query is modeled by the `getArtist()` method
which returns an artist object that does not contain the `albumCount` field, and the `getArtistWithAlbumCount()` method
which returns an artist object that contains the `albumCount` field. Similarly, the `artists` query is modeled by
the `getArtists()` method and the `getArtistsWithAlbumCount()` method. The `getArtists()` method returns artist objects
that do not contain the `albumCount` field and the `getArtistsWithAlbumCount()` method returns artist objects that
contain the `albumCount` field.

ArtistService.java
[source,java,linenums,role='code_column hide_tags=comment']
----
include::src/test/java/io/openliberty/guides/graphql/client/models/ArtistWithAlbumCount.java[]
----

ArtistServiceAPI.java
[source,java,linenums,role='code_column hide_tags=comment']
----
include::src/test/java/io/openliberty/guides/graphql/client/ArtistServiceAPI.java[]
----

=== Creating the test class

[role="code_command hotspot", subs="quotes"]
----
#Create the `ArtistServiceIT` class.#
`src/test/java/io/openliberty/graphql/ArtistServiceIT.java`
----



ArtistServiceIT.java
[source,java,linenums,role='code_column hide_tags=comment']
----
include::src/test/java/io/openliberty/guides/graphql/ArtistServiceIT.java[]
----

[role='command']
link:https://raw.githubusercontent.com/OpenLiberty/guides-common/master/devmode-test.adoc[]

[role='command']
link:https://raw.githubusercontent.com/OpenLiberty/guides-common/master/devmode-quit.adoc[]


== Great work! You're done!

//--** Briefly summarize what the user achieved in this guide (1-2 sentences).
EXAMPLE: You have just completed building a simple todo list application using JAXRS and CDI services in Open Liberty.

//--** OPTIONAL: briefly state what the user could do next now that they've learned the
//--** technologies in this guide.

//--** Include the below from the guides-common repo to tell users how they can contribute to the guide
link:https://raw.githubusercontent.com/OpenLiberty/guides-common/master/attribution.adoc[]

//--** DO NO CREATE ANYMORE SECTIONS AT THIS POINT
//--** Related guides will be added in automatically here if you included them in ":page-related-guides"
// ------------ END ------------