//  Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: social-login
:page-layout: guide-multipane
:page-duration: 30 minutes
:page-releasedate: 2020-06-20
:page-essential: true
:page-essential-order: 1
:page-description: Learn how to authenticate users with the Open Liberty Social Media Login feature.
:guide-author: Open Liberty
:page-tags: ['Java EE', 'Jakarta EE', 'Security']
:page-related-guides: ['microprofile-jwt']
:page-permalink: /guides/{projectid}
:page-seo-title: Authenticating users with Social Media Login
:page-seo-description: A getting started tutorial with examples on how to secure Java applications by authenticating users through social media providers, such as GitHub, using the Open Liberty Social Media Login feature.
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
= Authenticating users through social media providers

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website^].

A getting started tutorial with examples on how to secure Java applications by authenticating users through social media
providers, such as GitHub, using the Open Liberty Social Media Login feature.

== What you'll learn

Social Media Login provides a form of single sign-on (SSO) which users can use to sign in to a secured website with
their existing social media account.
It simplifies the authentication process for users and allows you to provide a secure authentication
method for your users without having to explicitly implement it.

The https://openliberty.io/docs/ref/feature/#socialLogin-1.0.html[Social Media Login Feature^] in Open Liberty
provides configuration elements to configure application authentication using one or more social media platforms,
including GitHub&reg;, LinkedIn&reg;, Facebook&reg;, Twitter&reg;, and Google&reg;.
You can also create a custom configuration for any other social media platform that implements
the https://oauth.net/2[OAuth 2.0^] or https://openid.net/connect[OpenID Connect 1.0^] standard for authorization.

By the end of this guide, you will be able to use GitHub to authenticate users to your web service.

// =================================================================================================
// Getting Started
// =================================================================================================
[role='command']
include::{common-includes}/gitclone.adoc[]

== Creating a GitHub&reg; OAuth2 Application

Obtain an OAuth 2.0 client ID and client secret credentials for accessing the GitHub&reg; developer API by registering
a new application in your https://github.com/[GitHub&reg;^] account.
On the https://github.com/settings/developers[Settings > Developer settings > OAuth Apps^] page of your account,
register a new application.

Set the Homepage URL to `\https://localhost:9443` and
the authorization callback URL to `\https://localhost:9443/ibm/api/social-login/redirect/githubLogin`.

When the registration is complete, the client ID and client secret credentials are displayed.
To provide your application with the credentials, export the following environment variables: `GITHUB_CLIENT_ID` and
`GITHUB_CLIENT_SECRET`.

Replace the values of `[github-client-id]` and `[github-client-secret]` in the following command.
include::{common-includes}/os-tabs.adoc[]
[.tab_content.mac_section.linux_section]
--
[role='command']
----
export GITHUB_CLIENT_ID=[github-client-id]
export GITHUB_CLIENT_SECRET=[github-client-secret]
----
--
[.tab_content.windows_section]
--
[role='command']
----
set GITHUB_CLIENT_ID=[github-client-id]
set GITHUB_CLIENT_SECRET=[github-client-secret]
----
--

== Configuring GitHub&reg; social media login
In the `start` directory, you are provided with an application that is secured through `BASIC` authentication.
When you access the `hello.html` page, find the `login` button.

Clicking the `login` button opens a login dialog that requests a username and password for
`defaultRealm`.
Enabling the Social Login feature will replace the login dialogue with social media login.

First, navigate to the `start` directory.

[role='command']
include::{common-includes}/devmode-start.adoc[]

[role="code_command", subs="quotes"]
----
#Update this `server.xml` file.#
`src/main/liberty/config/server.xml`
----
[role="edit_command_text"]
Add the `socialLogin-1.0` feature definition to the existing list of features.
Add the `<githubLogin />` configuration element to the server configuration.

Adding the `socialLogin-1.0` feature definition enables social media login functionality to
the application, which allows you to use the `<githubLogin />` configuration element to
configure GitHub&reg; login.

The client ID and client secret for your GitHub&reg; OAuth2 application are injected into the
`<githubLogin />` configuration element with the values of `github.client.id` and
`github.client.secret`.
These values are supplied by the environment variables `GITHUB_CLIENT_ID` and `GITHUB_CLIENT_SECRET`.

// =================================================================================================
// Building the application
// ================================================================================================
[role='command']
include::{common-includes}/devmode-build.adoc[]

Check out the service that you created at
http://localhost:9080/api/hello.html[^].

Try logging in with your social media account.
After authentication, you are redirected to the `/hello` endpoint served by
`HelloServlet`, which serves the
`securedHello.jsp` page.

The `securedHello.jsp` page contains a `logout` button that makes a
`POST` request to the `/logout` endpoint served by `LogoutServlet`.

Since the logout feature is not fully implemented, clicking the logout button returns an error:

[role='no_copy']
----
 Exception thrown by application class 'io.openliberty.guides.sociallogin.LogoutServlet.doPost:50'
java.lang.NullPointerException:
at io.openliberty.guides.sociallogin.LogoutServlet.doPost(LogoutServlet.java:50)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:706)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1230)
at [internal classes]
----

== Implementing logout

The `LogoutServlet` provided in the `start` directory uses the
`logout()` method in the `HttpServletRequest`.
class to log the user out of the application after which the user is redirected to
`hello.html`.

You are also provided with a `LogoutHandler` class and `ILogout` interface to add
custom logout logic to revoke the application's permissions from a user's account.

The `logoutHandler.getLogout()` method gets an implementation
of `ILogout` for GitHub&reg; and uses the `logout()` method of the `ILogout` interface to revoke
OAuth2 permissions that are granted to the application by the user.

The response returned by this `logout()` method is verified by checking whether it has a
`2xx` series status code.

The `request.logout()` method is then called to log the user out of the
application.

The `logoutHandler.getLogout()` method `returns` the
`implementation` of `ILogout` based on the name of the social media provider that is used
by a user. The social media provider's name is retrieved by using the
`UserProfileManager`.
The social media provider's name that is returned by `UserProfileManager` is the `id`
of the login configuration.

In this case, when the user uses GitHub&reg;, the name of the social media provider is
`githubLogin`.

Implement `ILogout` for revoking permissions for the application from the user's GitHub&reg; account.

[role="code_command", subs="quotes"]
----
#Replace this `GitHubLogout` class.#
`src/main/java/io/openliberty/guides/sociallogin/logout/GitHubLogout.java`
----

GitHub&reg;'s REST API provides a `DELETE` `endpoint` that is used to revoke permissions
from the user for the application.
The JAX-RS `HttpClient` is used to send a request to this endpoint.

The `encoded` client ID and client secret, obtained from the `github.client.id` and
`github.client.secret` config properties are added to the request as an
`Authorization` header.

The GitHub&reg; `access token` that is retrieved from the user's `UserProfile` through the
`UserProfileManager` is sent as part of the
`request body`.

// =================================================================================================
// Running the application
// ================================================================================================
The Open Liberty server was started in development mode at the beginning of the guide and all the changes were
automatically picked up.

Check out the service that you created at
http://localhost:9080/api/hello.html[^].

Try logging in with your social media account.
After authenticating, you will be redirected to `\https://localhost:9080/api/hello`.
When you click the `logout` button, you are unauthenticated and redirected back to
http://localhost:9080/api/hello.html[^].

If you try logging in again, you are asked to reauthorize your application with GitHub&reg;, and authenticated and
redirected to `\https://localhost:9080/api/hello`.

[role='command']
include::{common-includes}/devmode-quit.adoc[]

== Great work! You're done!

You secured a web application in Open Liberty by using the Social Media Login feature.

== Next steps

As an exercise, configure Facebook&reg; as a second social media provider for social media login for your application.
If more than one social media login provider is added, a selection form is presented to the user. This form contains
all the possible social media providers that are configured in your application.

Create the `<facebookLogin />` configuration element in `server.xml` to set up login for Facebook&reg;.
Similar to `<githubLogin />`, `<facebookLogin />` also requires only a client ID and client secret.

Then, implement `ILogout` as `FacebookLogout` for revoking permissions for the application from the Facebook&reg; user
account and update `LogoutHandler` to inject `FacebookLogout` and return it when the social media name is
`facebookLogin`.

The following links to Facebook&reg; documentation provides any additional information about setting up an OAuth2
application and revoking permissions.

- https://developers.facebook.com/docs/apps#register[Registering for a Facebook&reg; application^]
- https://developers.facebook.com/docs/facebook-login/web#redirecturl[Adding Facebook&reg; Login to your Facebook&reg; Application^]
- https://developers.facebook.com/docs/facebook-login/permissions/requesting-and-revoking#revokelogin[Revoking Facebook&reg; Login^]

== Related Links

Learn more about MicroProfile.

https://microprofile.io/[See the MicroProfile specs^]

https://openliberty.io/docs/ref/microprofile[View the MicroProfile API^]


include::{common-includes}/attribution.adoc[subs="attributes"]
